name: StartupCFO
favicon: null
layout_spectrum: 0.54016
typography_spectrum: 0.79649
title: The Startup CFO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.681400413857773
  lightness: 0.18028023862279952
  saturation: 0.2149888335261494
  rhythmicContrast: 0.3995346059091389
purpose: []
